# Generated by Django 6.0.4 on 2026-04-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buspass',
            name='approval_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='buspass',
            name='final_pass_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buspass',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
