# Generated by Django 6.0.4 on 2026-04-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_buspass_approval_id_buspass_final_pass_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buspass',
            name='pass_pdf',
            field=models.FileField(blank=True, null=True, upload_to='bus_pass_pdfs/'),
        ),
    ]
