# Generated by Django 6.0.4 on 2026-04-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_buspass_pass_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='buspass',
            name='renewal_requested',
            field=models.BooleanField(default=False),
        ),
    ]
