# Generated by Django 6.0.3 on 2026-04-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_buspass_renewal_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ssc_certificate',
            field=models.FileField(blank=True, null=True, upload_to='ssc_certificates/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='study_certificate',
            field=models.FileField(blank=True, null=True, upload_to='study_certificates/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='college_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
    ]
