# Generated by Django 6.0.3 on 2026-04-26 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_nongovernmentemployeeprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('route_from', models.CharField(max_length=100)),
                ('route_to', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=150)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose_of_travel', models.CharField(max_length=200)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='citizen_profiles/')),
                ('residence_proof', models.FileField(blank=True, null=True, upload_to='residence_proofs/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
